Feature/hw 7
emd-lsd/education_project pull request #6
Opened 2024-02-14 18:16 UTC by emd-lsd

2024-02-15 12:17 UTC, Parazit94 requested changes
В целом неплохо но я бы переделал создание животных и оптимизировал код

2024-02-15 12:17 UTC, Parazit94 commented on .idea/gradle.xml
не нужен

2024-02-15 12:17 UTC, Parazit94 commented on .idea/misc.xml
не нужен

2024-02-15 12:17 UTC, Parazit94 commented on animal_starter/src/main/java/ru/mtsstarter/animals/AnimalFactoryImpl.java
> +        animal.put("HAMSTER", new Hamster("", CreateAnimalServiceImpl.generateCost(), CreateAnimalServiceImpl.generateCharacter(), CreateAnimalServiceImpl.generateBirthDay()));
не понял зачем ты инжектишь имена но при это у тебя все животные без имени

2024-02-15 12:17 UTC, Parazit94 commented on animal_starter/src/main/java/ru/mtsstarter/service/CreateAnimalServiceImpl.java
>      static final String[] names = {"Simba", "Rex", "Whiskers", "Fluffy", "Dumbo", "Jerry", "Tom", "Nemo", "Mikky"}; // клички
зачем оставил?

2024-02-15 12:17 UTC, Parazit94 commented on animal_starter/src/main/java/ru/mtsstarter/service/CreateAnimalServiceImpl.java
> +    public static String generateName() {
не используется

2024-02-15 12:17 UTC, Parazit94 commented on animal_starter/src/main/java/ru/mtsstarter/service/CreateAnimalServiceImpl.java
> +    public static BigDecimal generateCost() {
я бы вынес всю статику в фактори

2024-02-15 12:17 UTC, Parazit94 commented on src/main/java/ru/mts/ScheduledTask.java
> +        Animal[] animals = new Animal[]{
почему у тебя все статично?

2024-02-15 18:21 UTC, emd-lsd commented on .idea/misc.xml
Удалил, после запуска создается автоматически

2024-02-15 18:21 UTC, emd-lsd commented on .idea/gradle.xml
Тоже удалил, после запуска проекта создается автоматически idea

2024-02-15 19:30 UTC, emd-lsd commented on src/main/java/ru/mts/ScheduledTask.java
> +        Animal[] animals = new Animal[]{
Не понял про что ты, если ты про статичное создание в этом месте животных, то здесь специально создавал животных с дубликатами и добавлял их уже в массив, чтобы проверять работоспособность метода по поиску дубликатов

2024-02-16 14:11 UTC, Parazit94 commented on animal_starter/src/main/java/ru/mtsstarter/service/CreateAnimalServiceImpl.java
> +    public String generateRandomName() {
сделай приватным, он используется только внутри класса

2024-02-16 15:11 UTC, merged